var PIANO_TRANSLATION = {
    url: "piano?",
    buttonNames: {
        markNotes: "Đánh dấu",
        showHideNotes: {
            show: "Hiển thị nốt nhạc",
            hide: "Ẩn nốt nhạc",
        },
        playNotes: "Chơi",
        reset: "Xoá",
    },
    noteNames: {
        c: "Đô",
        cis: '<span><span>Đô</span><span class="accidental">♯</span></span>' + '<span><span>Rê</span><span class="accidental">♭</span></span>',
        d: "Rê",
        dis: '<span><span>Rê</span><span class="accidental">♯</span></span>' + '<span><span>Mi</span><span class="accidental">♭</span></span>',
        e: "Mi",
        f: "Fa",
        fis: '<span><span>Fa</span><span class="accidental">♯</span></span>' + '<span><span>Sol</span><span class="accidental">♭</span></span>',
        g: "Sol",
        gis: '<span><span>Sol</span><span class="accidental">♯</span></span>' + '<span><span>La</span><span class="accidental">♭</span></span>',
        a: "La",
        ais: '<span><span>La</span><span class="accidental">♯</span></span>' + '<span><span>Si</span><span class="accidental">♭</span></span>',
        b: "Si",
    },
    keys: {
        "1c": [90],
        "1cis": [83],
        "1d": [88],
        "1dis": [68],
        "1e": [67],
        "1f": [81],
        "1fis": [50],
        "1g": [87],
        "1gis": [51],
        "2a": [69],
        "2ais": [52],
        "2b": [82],
        "2c": [84],
        "2cis": [54],
        "2d": [89],
        "2dis": [55],
        "2e": [85],
        "2f": [73],
        "2fis": [57],
        "2g": [79],
        "2gis": [48],
        "3a": [80],
        "3ais": [187, 189, 173, 8],
        "3b": [219],
        "3c": [221],
        "3cis": [70],
        "3d": [86],
        "3dis": [71],
        "3e": [66],
        "3f": [78],
        "3fis": [74],
        "3g": [77],
        "3gis": [75],
        "4a": [188],
        "4ais": [76],
        "4b": [190],
    },
};
